version: '3.8'

services:
  # MLflow Tracking Server
  mlflow:
    image: python:3.11-slim
    container_name: mlflow-server
    working_dir: /app
    volumes:
      - ./mlruns:/home/thamaraikannan/Desktop/project1/mlruns
      - ./backend:/app/backend
    ports:
      - "5000:5000"
    command: >
      bash -c "pip install mlflow && mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri file:///app/mlruns"
    restart: unless-stopped

  # Churn Prediction API
  churn-api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: churn-api:latest
    container_name: churn-api
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/home/thamaraikannan/Desktop/project1/mlruns
      - ./backend:/app/backend
      - ./training:/app/training
      - ./frontend:/app/frontend
    environment:
      - WORKERS=4
      - MLFLOW_TRACKING_URI=file:///home/thamaraikannan/Desktop/project1/mlruns
    depends_on:
      - mlflow
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
